### ISSUE TITLE
加载本地模型报错

### ISSUE THREAD

**Issue by watersliang** [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker#13]
大佬你好

我在加载本地模型的时候，超时了。

![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/assets/76990369/bc86c9c8-9318-4a73-b348-ba76875723ed)
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2334, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2332, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2320, in get_cache
    json_obj = await get_data(uri)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 530, in get_data
    async with session.get(uri) as resp:
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [Connect call failed ('185.199.109.133', 443)]

另外，请教下，模型加载支持windows的绝对路径么？

**Comment by watersliang** [comment]
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/assets/76990369/33cc0112-0a67-4224-b9b5-6fd955cf72f3)
我使用的是大佬提供的默认本地工作流

**Comment by fs920105** [comment]
你提供的这个是管理器连不上github的报错日志

**Comment by AdamShuo** [comment]
这个是由于SSL验证失败导致无法从github下载XL模型配置文件产生的报错，我也碰到了，不知道怎么解决。

**Comment by watersliang** [comment]
> b

我可以自己去下载配置文件放到指定路径么？

**Comment by AdamShuo** [comment]
> > b
> 
> 我可以自己去下载配置文件放到指定路径么？

不知道放哪儿
