### ISSUE TITLE
TypeError: _get_model_file() got an unexpected keyword argument 'token'

### ISSUE THREAD

**Issue by fagemx** [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker#21]
嗨嗨，卡在以下報錯，有更新confyUI，能請教這是什麼問題嗎?謝謝

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\PhotoMakerNode.py", line 150, in load_photomaker_adapter
    pipe.load_photomaker_adapter(
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\pipeline.py", line 80, in load_photomaker_adapter
    model_file = _get_model_file(
TypeError: _get_model_file() got an unexpected keyword argument 'token'

**Comment by cardenluo** [comment]
同样的问题，解决了吗？

**Comment by cardenluo** [comment]
pip install --upgrade diffusers

**Comment by fagemx** [comment]
有，更新後解決，謝謝
