### ISSUE TITLE
"_get_model_file() got an unexpected keyword argument 'token'"

### ISSUE THREAD

**Issue by danganbenpa** [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker#22]
Error occurred when executing PhotoMakerAdapter_Loader_local:

_get_model_file() got an unexpected keyword argument 'token'

File "D:\Users\Ben\comfyui\ComfyUI\execution.py", line 155, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Users\Ben\comfyui\ComfyUI\execution.py", line 85, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Users\Ben\comfyui\ComfyUI\execution.py", line 78, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Users\Ben\comfyui\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\PhotoMakerNode.py", line 150, in load_photomaker_adapter
pipe.load_photomaker_adapter(
File "D:\Users\Ben\comfyui\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "D:\Users\Ben\comfyui\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\pipeline.py", line 80, in load_photomaker_adapter
model_file = _get_model_file(

**Comment by wandrzej** [comment]
+1 
had the same error with both the hub version and local version

**Comment by razvanab** [comment]
Same error here, please help.

**Comment by AI2lab** [comment]
solution:
pip install diffusers --upgrade

**Comment by razvanab** [comment]
Ok, now I get this error:

` ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\DEV\REPOS\Stable-diffusion\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\PhotoMakerNode.py", line 80, in load_model
    pipe = PhotoMakerStableDiffusionXLPipeline.from_single_file(
  File "H:\DEV\Conda\envs\comfy\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "H:\DEV\Conda\envs\comfy\lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "H:\DEV\Conda\envs\comfy\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1687, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: StableDiffusionXLPipeline.__init__() got an unexpected keyword argument 'safety_checker' `

**Comment by KINGLIFER** [comment]
didnt work for me.

**Comment by ludogemma** [comment]
found solution go in your \ComfyUI\ComfyUI\custom_nodes\ directory from cmd then write:
example C:\Users\name\ComfyUI\python_embeded
\python.exe -s -m pip install -r ./requirements.txt
then after finish
C:\Users\name\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker>C:\Users\Sergio\ComfyUI\python_embeded\python.exe -s -m pip install diffusers --upgrade

this way you install requirements and diffusers upgrade on the embeded python instead system python.

hope that helps ;)
