### ISSUE TITLE
 (IMPORT FAILED): \ComfyUI\custom_nodes\ComfyUI-PhotoMaker

### ISSUE THREAD

**Issue by zhoobin021** [ZHO-ZHO-ZHO/ComfyUI-PhotoMaker#30]
I tried reinstalling, 
I did
git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker.git 
and also did 'pip install -r requirements.txt' inside 'custom_nodes/ComfyUI-PhotoMaker'

even did git pull in 'custom_nodes/ComfyUI-PhotoMaker' folder and It says it's already up to date.
but still getting the '(IMPORT FAILED): \ComfyUI\custom_nodes\ComfyUI-PhotoMaker' error and the nodes inside the 'PhotoMaker_locally【Zho】.json' workflow are red and undefined.

please help. thank you.

**Comment by GraftingRayman** [comment]
do a "pip install -r requirements.txt" in the CustomUI-PhotoMaker" folder

This will get you your missing nodes

**Comment by zhoobin021** [comment]
> do a "pip install -r requirements.txt" in the CustomUI-PhotoMaker" folder
> 
> This will get you your missing nodes

I did do that, it didn't work.

**Comment by cvar66** [comment]
It's not working because you are using the portable version and it is installing the requirements in the wrong folders. Type this in the CustomUI-PhotoMaker folde and change the path to python embedded to the path on your pc 

E:\SD\comfy2\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install -r ./requirements.txt

**Comment by prosperinweb** [comment]
Am also getting this error, am using ComfyUI via Stability Matrix and ran through the steps as indicates but the nodes fail to load.

**Comment by ceramicwhite** [comment]
Yep the commits in the last 24 hours broke the nodes.

Just checkout to yesterdays commit 349f577 for now and use the v2.0 workflows:
[PhotoMaker_fromhub【Zho】.json](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/blob/main/PhotoMaker%20Workflows/PhotoMaker_fromhub%E3%80%90Zho%E3%80%91.json)
[PhotoMaker_locally【Zho】.json](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/blob/main/PhotoMaker%20Workflows/PhotoMaker_locally%E3%80%90Zho%E3%80%91.json)

`cd custom_nodes/ComfyUI-PhotoMaker &&
git checkout 349f577`

**Comment by ponponych** [comment]
![2024-01-20_073507](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/assets/120938885/d3a450ae-88b9-47fb-abb8-272ad09d91d4)
![2024-01-20_073610](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/assets/120938885/a8b3381e-f586-435b-9fa2-8ebe4a4fceb8)

**Comment by ceramicwhite** [comment]
@ponponych 
<img width="648" alt="Screenshot 2024-01-19 at 9 21 05 PM" src="https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/assets/7660824/c911c6d6-fbc9-4667-a6ba-37db915e29ed">
You've got something else going on, check your logs.

**Comment by ponponych** [comment]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\__init__.py", line 1, in <module>
    from .PhotoMakerNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\PhotoMakerNode.py", line 4, in <module>
    from diffusers.utils import load_image
ModuleNotFoundError: No module named 'diffusers'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker module for custom nodes: No module named 'diffusers'

**Comment by ceramicwhite** [comment]
@ponponych 
run `pip install -r requirements.txt` inside `F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker`

**Comment by ponponych** [comment]
Launched. All the same.

**Comment by prosperinweb** [comment]
So I also ran the pip command and it this is a snippet of where the dependencies installed. Is the path maybe the problem?

```bash
ofent@Prosper MINGW64 ~/AppData/Roaming/StabilityMatrix/Packages/ComfyUI/custom_nodes/ComfyUI-PhotoMaker (main)
$ pip install -r requirements.txt
Requirement already satisfied: diffusers==0.25.0 in c:\users\ofent\miniconda3\lib\site-packages (from -r requirements.txt (line 1)) (0.25.0)
Requirement already satisfied: transformers==4.36.2 in c:\users\ofent\miniconda3\lib\site-packages (from -r requirements.txt (line 2)) (4.36.2)
Requirement already satisfied: huggingface-hub==0.20.2 in c:\users\ofent\miniconda3\lib\site-packages (from -r requirements.txt (line 3)) (0.20.2)
```

**Comment by leifniem** [comment]
https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/issues/15#issuecomment-1898701609

This comment probably has the solution. It did for me. Hope that helps.

**Comment by zhoobin021** [comment]
> [#15 (comment)](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/issues/15#issuecomment-1898701609)
> 
> This comment probably has the solution. It did for me. Hope that helps.

Yes, thank you, this worked!

just to make sure everyone can do it:

-go to ComfyUI\custom_nodes directory and in the search bar of the folder type cmd and press enter.
-paste this : git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker.git
-press enter
-then go to ComfyUI_windows_portable\python_embeded directory and in the search bar of the folder type cmd and press enter.
-paste this : python.exe -m pip install -r path_to_requirements
-replace path_to_requirements with the directory of requirements.txt wherever your comfyui is installed, 
e.g. D:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\requirements.txt.
together it should look similar like this : 

python.exe -m pip install -r D:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\requirements.txt.

-press enter and wait a bit,
-then restart comfyui and test to see if the nodes are activated.

**Comment by hidogo** [comment]
> I tried reinstalling, I did git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker.git and also did 'pip install -r requirements.txt' inside 'custom_nodes/ComfyUI-PhotoMaker'
> 
> even did git pull in 'custom_nodes/ComfyUI-PhotoMaker' folder and It says it's already up to date. but still getting the '(IMPORT FAILED): \ComfyUI\custom_nodes\ComfyUI-PhotoMaker' error and the nodes inside the 'PhotoMaker_locally【Zho】.json' workflow are red and undefined.
> 
> please help. thank you.

same problem

**Comment by hidogo** [comment]
> ![2024-01-20_073507](https://private-user-images.githubusercontent.com/120938885/298255896-d3a450ae-88b9-47fb-abb8-272ad09d91d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTUyOTEsIm5iZiI6MTcwNTgxNDk5MSwicGF0aCI6Ii8xMjA5Mzg4ODUvMjk4MjU1ODk2LWQzYTQ1MGFlLTg4YjktNDdmYi1hYmI4LTI3MmFkMDlkOTFkNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwNTI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDgzOTFiOWUyOTI3YzBiMmE0ZTgxMGIzM2E5MDlmMDQ5N2FjNzJlYmNiMmEzNzMxYTUzZTNlZjhkNDUxODZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8r1s63a07QAaiCZJ6UJ5jOSqK5UnZCYKEv3IPhrkAkY) ![2024-01-20_073610](https://private-user-images.githubusercontent.com/120938885/298255902-a8b3381e-f586-435b-9fa2-8ebe4a4fceb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTUyOTEsIm5iZiI6MTcwNTgxNDk5MSwicGF0aCI6Ii8xMjA5Mzg4ODUvMjk4MjU1OTAyLWE4YjMzODFlLWY1ODYtNDM1Yi05ZmEyLThlYmU0YTRmY2ViOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwNTI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTg5Y2RkYzM4ODEzMzJiMjNmOGJiYmU0ZDc2MWE1NDRkOGU4NWI1MzM4M2Q5ODlmZmE0ZGExOWE1NTIwNDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RdBRBS5WgHWFSU1eFhq_vDixGYu5x01ptfvXANt16Jw)

Having the same problem

**Comment by leifniem** [comment]
> same problem

Check the comment right above yours

**Comment by LuisBurdallo** [comment]
> > [#15 (comment)](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/issues/15#issuecomment-1898701609)
> > This comment probably has the solution. It did for me. Hope that helps.
> 
> Yes, thank you, this worked!
> 
> just to make sure everyone can do it:
> 
> -go to ComfyUI\custom_nodes directory and in the search bar of the folder type cmd and press enter. -paste this : git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker.git -press enter -then go to ComfyUI_windows_portable\python_embeded directory and in the search bar of the folder type cmd and press enter. -paste this : python.exe -m pip install -r path_to_requirements -replace path_to_requirements with the directory of requirements.txt wherever your comfyui is installed, e.g. D:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\requirements.txt. together it should look similar like this :
> 
> python.exe -m pip install -r D:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\requirements.txt.
> 
> -press enter and wait a bit, -then restart comfyui and test to see if the nodes are activated.

I tried that but the Photomaker Generation node is still missing.

**Comment by LuisBurdallo** [comment]
Anyone with this problem  watch  this video cause it helped me solving that problem. Now the problem is the paths are not recognized in order to load the adapter.

https://www.youtube.com/watch?v=yjCa9WALzAs

**Comment by zhoobin021** [comment]
> > > [#15 (comment)](https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker/issues/15#issuecomment-1898701609)
> > > This comment probably has the solution. It did for me. Hope that helps.
> > 
> > 
> > Yes, thank you, this worked!
> > just to make sure everyone can do it:
> > -go to ComfyUI\custom_nodes directory and in the search bar of the folder type cmd and press enter. -paste this : git clone https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker.git -press enter -then go to ComfyUI_windows_portable\python_embeded directory and in the search bar of the folder type cmd and press enter. -paste this : python.exe -m pip install -r path_to_requirements -replace path_to_requirements with the directory of requirements.txt wherever your comfyui is installed, e.g. D:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\requirements.txt. together it should look similar like this :
> > python.exe -m pip install -r D:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker\requirements.txt.
> > -press enter and wait a bit, -then restart comfyui and test to see if the nodes are activated.
> 
> I tried that but the Photomaker Generation node is still missing. The problem must be for those (like me) with a portable version. Something isn't installing properly.

yes, you just need to update the Photomaker (git pull) and then replace it with NEW Photomager Generation node

**Comment by prosperinweb** [comment]
> Anyone with this problem watch this video cause it helped me solve that problem.
> 
> https://www.youtube.com/watch?v=yjCa9WALzAs

Solved my problem, for those using Stability Matrix as your ComfyUI package manager, go to your custom_nodes/ComfyUI-PhotoMaker folder and pip install using 

C:\Users\[your username]\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\Scripts\pip install -r requirments.txt
